version: '3'
services:
  redis:
    image: redis/redis-stack-server:latest
    command: sh -c "redis-stack-server"
    networks:
      - local
    ports: 
      - 6379:6379

networks: 
  local:
    driver: bridge