version: '3'
services:
  redis:
    image: redis:6.2.8
    command: redis-server --requirepass password
    networks:
      - local
    ports: 
      - 6379:6379

networks: 
  local:
    driver: bridge