service: matching-engine-api-goerli
runtime: nodejs
env: flex
entrypoint: npm run start
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.5
resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10
readiness_check:
  app_start_timeout_sec: 1800
env_variables:
  MATCHING_ENGINE: 1
  EXECUTION_ENGINE: 1
  API_READONLY: 1
  CHAIN_ID: 5
vpc_access_connector:
  name: projects/nftc-infinity/locations/us-east1/connectors/cloud-sql-vpc-connector
